#!/bin/bash -e

chown -R postgres:postgres /var/lib/postgresql/9.3/main
chown -R postgres:postgres /var/log/postgresql
chown -R postgres:postgres /etc/postgresql/9.3/main/conf.d

mydb=${POSTGRESQL_DATABASE:-""}
myuser=${POSTGRESQL_USER:-""}
mypass=${POSTGRESQL_PASSWORD:-""}
mychset=${POSTGRESQL_CHARACTER_SET:-"utf8"}
myhost=${GRANT_HOSTNAME:-"%"}

#if [[ $mydb != "" ]]; then
#    echo "CREATE DATABASE IF NOT EXISTS \`$mydb\` CHARACTER SET \`$mychset\` COLLATE \`$mycollate\`;" >> $tfile
#
#    if [[ $myuser != "" ]]; then
#        echo "GRANT ALL ON \`$mydb\`.* TO '$myuser'@'$myhost' IDENTIFIED BY '$mypass';" >> $tfile
#    fi
#fi

exec supervisord
